name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 1. Pre-install Flutter so Flet doesn't have to ask
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - name: Install Dependencies
        run: |
          pip install flet yfinance pandas numpy flet-cli

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          # Added --android-permissions to allow the app to fetch live rates
          flet build apk --yes --verbose --android-permissions "android.permission.INTERNET"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ethio-Forex-AI-Mobile
          path: build/apk/*.apk