name: Build Android APK
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install flet yfinance pandas joblib

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - name: Build APK
        run: |
          flet build apk -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ethio-Forex-App
          path: build/apk/*.apk
