name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Clears the deprecation warning
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet yfinance pandas joblib scikit-learn numpy

      - name: Build APK
        run: |
          # The --verbose flag will help us see exactly where it fails if it does
          flet build apk --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ethio-Forex-AI-Mobile
          path: build/apk/*.apk